export const VOICES = [
  {
    id: "zephyr",
    name: "Zephyr",
    description: "Bright, Higher pitch",
    sampleUrl: "https://gstatic.com/aistudio/voices/samples/Zephyr.wav",
  },
  {
    id: "puck",
    name: "Puck",
    description: "Upbeat, Middle pitch",
    sampleUrl: "https://gstatic.com/aistudio/voices/samples/Puck.wav",
  },
  {
    id: "charon",
    name: "Charon",
    description: "Informative, Lower pitch",
    sampleUrl: "https://gstatic.com/aistudio/voices/samples/Charon.wav",
  },
  {
    id: "kore",
    name: "Kore",
    description: "Firm, Middle pitch",
    sampleUrl: "https://gstatic.com/aistudio/voices/samples/Kore.wav",
  },
  {
    id: "fenrir",
    name: "Fenrir",
    description: "Excitable, Lower middle pitch",
    sampleUrl: "https://gstatic.com/aistudio/voices/samples/Fenrir.wav",
  },
  {
    id: "leda",
    name: "Leda",
    description: "Youthful, Higher pitch",
    sampleUrl: "https://gstatic.com/aistudio/voices/samples/Leda.wav",
  },
  {
    id: "orus",
    name: "Orus",
    description: "Firm, Lower middle pitch",
    sampleUrl: "https://gstatic.com/aistudio/voices/samples/Orus.wav",
  },
  {
    id: "aoede",
    name: "Aoede",
    description: "Breezy, Middle pitch",
    sampleUrl: "https://gstatic.com/aistudio/voices/samples/Aoede.wav",
  },
  {
    id: "callirrhoe",
    name: "Callirrhoe",
    description: "Easy-going, Middle pitch",
    sampleUrl: "https://gstatic.com/aistudio/voices/samples/Callirrhoe.wav",
  },
  {
    id: "autonoe",
    name: "Autonoe",
    description: "Bright, Middle pitch",
    sampleUrl: "https://gstatic.com/aistudio/voices/samples/Autonoe.wav",
  },
  {
    id: "enceladus",
    name: "Enceladus",
    description: "Breathy, Lower pitch",
    sampleUrl: "https://gstatic.com/aistudio/voices/samples/Enceladus.wav",
  },
  {
    id: "iapetus",
    name: "Iapetus",
    description: "Clear, Lower middle pitch",
    sampleUrl: "https://gstatic.com/aistudio/voices/samples/Iapetus.wav",
  },
  {
    id: "umbriel",
    name: "Umbriel",
    description: "Easy-going, Lower middle pitch",
    sampleUrl: "https://gstatic.com/aistudio/voices/samples/Umbriel.wav",
  },
  {
    id: "algieba",
    name: "Algieba",
    description: "Smooth, Lower pitch",
    sampleUrl: "https://gstatic.com/aistudio/voices/samples/Algieba.wav",
  },
  {
    id: "despina",
    name: "Despina",
    description: "Smooth, Middle pitch",
    sampleUrl: "https://gstatic.com/aistudio/voices/samples/Despina.wav",
  },
  {
    id: "nPczCjzI2devNBz1zQrb",
    name: "Erinome",
    description: "Premium Voice",
    sampleUrl: "",
  },
  {
    id: "algenib",
    name: "Algenib",
    description: "Gravelly, Lower pitch",
    sampleUrl: "https://gstatic.com/aistudio/voices/samples/Algenib.wav",
  },
  {
    id: "rasalgethi",
    name: "Rasalgethi",
    description: "Informative, Middle pitch",
    sampleUrl: "https://gstatic.com/aistudio/voices/samples/Rasalgethi.wav",
  },
  {
    id: "laomedeia",
    name: "Laomedeia",
    description: "Upbeat, Higher pitch",
    sampleUrl: "https://gstatic.com/aistudio/voices/samples/Laomedeia.wav",
  },
  {
    id: "achernar",
    name: "Achernar",
    description: "Soft, Higher pitch",
    sampleUrl: "https://gstatic.com/aistudio/voices/samples/Achernar.wav",
  },
  {
    id: "alnilam",
    name: "Alnilam",
    description: "Firm, Lower middle pitch",
    sampleUrl: "https://gstatic.com/aistudio/voices/samples/Alnilam.wav",
  },
  {
    id: "schedar",
    name: "Schedar",
    description: "Even, Lower middle pitch",
    sampleUrl: "https://gstatic.com/aistudio/voices/samples/Schedar.wav",
  },
  {
    id: "gacrux",
    name: "Gacrux",
    description: "Mature, Middle pitch",
    sampleUrl: "https://gstatic.com/aistudio/voices/samples/Gacrux.wav",
  },
  {
    id: "pulcherrima",
    name: "Pulcherrima",
    description: "Forward, Middle pitch",
    sampleUrl: "https://gstatic.com/aistudio/voices/samples/Pulcherrima.wav",
  },
  {
    id: "achird",
    name: "Achird",
    description: "Friendly, Lower middle pitch",
    sampleUrl: "https://gstatic.com/aistudio/voices/samples/Achird.wav",
  },
  {
    id: "zubenelgenubi",
    name: "Zubenelgenubi",
    description: "Casual, Lower middle pitch",
    sampleUrl: "https://gstatic.com/aistudio/voices/samples/Zubenelgenubi.wav",
  },
  {
    id: "vindemiatrix",
    name: "Vindemiatrix",
    description: "Gentle, Middle pitch",
    sampleUrl: "https://gstatic.com/aistudio/voices/samples/Vindemiatrix.wav",
  },
  {
    id: "sadachbia",
    name: "Sadachbia",
    description: "Lively, Lower pitch",
    sampleUrl: "https://gstatic.com/aistudio/voices/samples/Sadachbia.wav",
  },
  {
    id: "sadaltager",
    name: "Sadaltager",
    description: "Knowledgeable, Middle pitch",
    sampleUrl: "https://gstatic.com/aistudio/voices/samples/Sadaltager.wav",
  },
  {
    id: "sulafat",
    name: "Sulafat",
    description: "Warm, Middle pitch",
    sampleUrl: "https://gstatic.com/aistudio/voices/samples/Sulafat.wav",
  },
] as const;

export type Voice = (typeof VOICES)[number];
